### ISSUE TITLE
How to get the JavaScript result from evaluate_script?

### ISSUE THREAD

**Issue by blankuserrr** [Amjad50/ul-next#9]

**Comment by Amjad50** [comment]
The return value for the function is `Result<Result<String, String>, CreationError>`, the first `Result` is related to `ultralight`, and it might return error if there was an issue with managing the strings based to `ultralight` and back, and this would normally stay `Ok`.

For the second `Result`, this is coming from executing javascript.
You get the result back as `Result<String, String>`, `Ok` in case of normal execution, `Err` in case of javascript error.

For example
`println!("{:?}", view.evaluate_script("1+1"));`

gives me `Ok(Ok("2"))`,

**Comment by blankuserrr** [comment]
Thanks for the info!

**Comment by blankuserrr** [comment]
@Amjad50 How do I send data between Rust->JS and JS->Rust?

**Comment by Amjad50** [comment]
Like what? Can you provide a simple example?

But anyway, ultralight provide a better interface for interacting with JavaScript. It's just I haven't implemented it yet, currently we only have `evaluate_script`, I'm planning to add support for the rest of his functionalities at some point.

**Comment by blankuserrr** [comment]
I simply want to pass the content of a text input to the rust output when a button is clicked in the html, however I'm struggling with that

**Comment by Amjad50** [comment]
Ah, Yes, we can do this with the javascript APIs which are under `JavaScriptCore`.

These are not implemented yet, I'm planning to add support, but busy with other stuff.
so you can't call rust from js now, but you can call js from rust with `evaluate_script`.

Added specific issue for this to keep me reminded #10

**Comment by Amjad50** [comment]
Hello @blankuserrr , added a better more complete javascript integration. Check [examples/javascript.rs](https://github.com/Amjad50/ul-next/blob/master/examples/javascript.rs)
